# fly.toml app configuration file generated for ph-smoketest-fs on 2023-09-09T22:13:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ph-smoketest-fs"
primary_region = "bos"

[experimental]
  auto_rollback = true

[build]

[env]
  SVC_PORT = "5050"

[[services]]
  protocol = "tcp"
  internal_port = 5050

  [[services.ports]]
    port = 5050

[[services]]
  protocol = "tcp"
  internal_port = 5050

  [[services.ports]]
    port = 5050
  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200
